### ISSUE TITLE
IOS crashes on xcode version 16.1 and using a simulator using ios 18.0

### ISSUE THREAD

**Issue by mattpearcefanhub** [Kebechet/Maui.MicrosoftClarity#7]
I've installed the most recent packages provided, however it consistently crashes on iOS. I'm running dotnet 9, maui 8.0.100 and the most recent packages for this wrapper.

My sim is iphone 16, running on iOS 18.0

Crash log:

```

ObjCRuntime.RuntimeException: Failed to lookup the required marshalling information.
Additional information:
	Selector: drawInContext:
	Type: Microsoft_Maui_Platform_MauiCALayer

 ---> ObjCRuntime.RuntimeException: Failed to get the 'this' instance in a method call to Microsoft.Maui.Platform.MauiCALayer.DrawInContext.
 ---> ObjCRuntime.RuntimeException: Failed to marshal the Objective-C object 0x60000098d5a0 (type: Microsoft_Maui_Platform_MauiCALayer). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'Microsoft.Maui.Platform.MauiCALayer' does not have a constructor that takes one NativeHandle argument).
   at ObjCRuntime.Runtime.MissingCtor(IntPtr ptr, IntPtr klass, Type type, MissingCtorResolution resolution, IntPtr sel, RuntimeMethodHandle method_handle) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1412
   at ObjCRuntime.Runtime.ConstructNSObject[NSObject](IntPtr ptr, Type type, MissingCtorResolution missingCtorResolution, IntPtr sel, RuntimeMethodHandle method_handle) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1543
   at ObjCRuntime.Runtime.ConstructNSObject[NSObject](IntPtr ptr, Type type, MissingCtorResolution missingCtorResolution) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1487
   at ObjCRuntime.Runtime.ConstructNSObject(IntPtr ptr, IntPtr klass, MissingCtorResolution missingCtorResolution) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1473
   at ObjCRuntime.Runtime.GetNSObject(IntPtr ptr, MissingCtorResolution missingCtorResolution, Boolean evenInFinalizerQueue) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1850
   at Registrar.DynamicRegistrar.GetMethodDescriptionAndObject(Type type, IntPtr selector, Boolean is_static, IntPtr obj, IntPtr& mthis, IntPtr desc) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/DynamicRegistrar.cs:line 1011
   --- End of inner exception stack trace ---
   at Registrar.DynamicRegistrar.GetMethodDescriptionAndObject(Type type, IntPtr selector, Boolean is_static, IntPtr obj, IntPtr& mthis, IntPtr desc) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/DynamicRegistrar.cs:line 1018
   at ObjCRuntime.Runtime.GetMethodAndObjectForSelector(IntPtr klass, IntPtr sel, SByte is_static, IntPtr obj, IntPtr* mthisPtr, IntPtr desc) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 977
   at ObjCRuntime.Runtime.get_method_and_object_for_selector(IntPtr cls, IntPtr sel, SByte is_static, IntPtr obj, IntPtr* mthis, IntPtr desc, IntPtr* exception_gchandle) in /Users/builder/azdo/_work/5/s/xamarin-macios/runtime/Delegates.generated.cs:line 712
   --- End of inner exception stack trace ---
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/UIKit/UIApplication.cs:line 61
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96
```

**Comment by Kebechet** [comment]
hmm, interesting. I am quite busy but in following week I will take a look

**Comment by mattpearcefanhub** [comment]
Thanks for the swift reply @Kebechet. I've just upgraded to xcode 16.2 and the maui packages to 9.0.14 but I'm still receiving the error I logged earlier this week 

Thank you again for your work and support, hopefully this is an easy fix on your side

**Comment by Kebechet** [comment]
I have updated iOS binding to `3.0.2` and wrapper to `1.0.8`.
Please test and let me know if it works.

**Comment by mattpearcefanhub** [comment]
Hi @Kebechet thank you so much for updating it so quickly. I've just tested it and unfortunately got the same error, do you have any further thoughts or recommendations? 

ObjCRuntime.RuntimeException
Failed to marshal the Objective-C object 0x6000007569c0 (type: Microsoft_Maui_Platform_MauiCALayer). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'Microsoft.Maui.Platform.MauiCALayer' does not have a constructor that takes one NativeHandle argument).

**Comment by mattpearcefanhub** [comment]
The full log from the debugger:

```
ObjCRuntime.RuntimeException: Failed to lookup the required marshalling information.
Additional information:
	Selector: drawInContext:
	Type: Microsoft_Maui_Platform_MauiCALayer

 ---> ObjCRuntime.RuntimeException: Failed to get the 'this' instance in a method call to Microsoft.Maui.Platform.MauiCALayer.DrawInContext.
 ---> ObjCRuntime.RuntimeException: Failed to marshal the Objective-C object 0x6000007d40a0 (type: Microsoft_Maui_Platform_MauiCALayer). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'Microsoft.Maui.Platform.MauiCALayer' does not have a constructor that takes one NativeHandle argument).
   at ObjCRuntime.Runtime.MissingCtor(IntPtr ptr, IntPtr klass, Type type, MissingCtorResolution resolution, IntPtr sel, RuntimeMethodHandle method_handle) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1412
   at ObjCRuntime.Runtime.ConstructNSObject[NSObject](IntPtr ptr, Type type, MissingCtorResolution missingCtorResolution, IntPtr sel, RuntimeMethodHandle method_handle) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1543
   at ObjCRuntime.Runtime.ConstructNSObject[NSObject](IntPtr ptr, Type type, MissingCtorResolution missingCtorResolution) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1487
   at ObjCRuntime.Runtime.ConstructNSObject(IntPtr ptr, IntPtr klass, MissingCtorResolution missingCtorResolution) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1473
   at ObjCRuntime.Runtime.GetNSObject(IntPtr ptr, MissingCtorResolution missingCtorResolution, Boolean evenInFinalizerQueue) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1850
   at Registrar.DynamicRegistrar.GetMethodDescriptionAndObject(Type type, IntPtr selector, Boolean is_static, IntPtr obj, IntPtr& mthis, IntPtr desc) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/DynamicRegistrar.cs:line 1011
   --- End of inner exception stack trace ---
   at Registrar.DynamicRegistrar.GetMethodDescriptionAndObject(Type type, IntPtr selector, Boolean is_static, IntPtr obj, IntPtr& mthis, IntPtr desc) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/DynamicRegistrar.cs:line 1018
   at ObjCRuntime.Runtime.GetMethodAndObjectForSelector(IntPtr klass, IntPtr sel, SByte is_static, IntPtr obj, IntPtr* mthisPtr, IntPtr desc) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 977
   at ObjCRuntime.Runtime.get_method_and_object_for_selector(IntPtr cls, IntPtr sel, SByte is_static, IntPtr obj, IntPtr* mthis, IntPtr desc, IntPtr* exception_gchandle) in /Users/builder/azdo/_work/5/s/xamarin-macios/runtime/Delegates.generated.cs:line 712
   --- End of inner exception stack trace ---
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/UIKit/UIApplication.cs:line 61
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96
   at FanHub.Program.Main(String[] args) in /Users/matthewpearce/Projects/FanHubMaui/Mobile.Maui/src/Platforms/iOS/Program.cs:line 13
```

**Comment by Kebechet** [comment]
interesting 🤔 It crashes during the build or during runtime ?
Can you try to test if the same problem happens in our [demo app](https://github.com/Kebechet/Maui.MicrosoftClarity/tree/main/demo/DemoApp) ?

**Comment by Kebechet** [comment]
even the demo app from my previous comment ?

**Comment by Kebechet** [comment]
Hu @mattpearcefanhub 
any update ? Did you try to run the demo app ?

**Comment by tobias-goldschmidt** [comment]
Hello @Kebechet and @mattpearcefanhub.

We are facing the same crash with "Failed to marshal the Objective-C", "drawInContext", "Microsoft_Maui_Platform_MauiCALayer" etc. and have been fighting this for a couple of days now.

I am fairly confident, that this crash happens as soon as you place a MAUI RadioButton anywhere on the page.

Your demo app does not crash because it consists only of razor pages. If you remove the BlazorWebView from the MainPage and add a RadioButton there somewhere, it also crashes with the same exception of this ticket (tested this just now).
Another indicator that it is the RadioButton is this bugfix from the official MAUI project, that references iOS, RadioButton and has a single line change in the class "MauiCALayer.cs":
https://github.com/dotnet/maui/pull/25542

For iOS there is no direct equivalent to a radio button so MAUI does some custom rendering of a button. That night be the reason this crash is pretty obscure and does not happen to a lot of people.

We already copied what you did in this repository, to use the newer SDK version 3.0.3 which has a bugfix labelled 
- [BugFix] Fixed crashes caused by layer color issues.

 but that also did not resolve the issue.

We are at a means end here and don't know how to proceed other than maybe redesigning our page to use something other than a RadioButton. Issue is happening locally on 

macOS 15.3, Xcode 16.2, iOS 18.2 (Simulator and iPhone), iOS 17.5 (Simulator)
pipeline build that crashes has macOS 14 and Xcode 16.1

Same result with MAUI 8.0.91 as with the latest 9.0.30

@mattpearcefanhub can you confirm that you are also using a RadioButton? If not, can you maybe try to single out one component that crashes your app?

**Comment by Kebechet** [comment]
in iOS native library they fixed many bugs since then. Maybe it got resolved?

Just today I bumped lib to iOS v3.5.2
https://learn.microsoft.com/en-us/clarity/mobile-sdk/sdk-changelog#352-april-29-2026
